#!/bin/bash

#usage enable_nat localif internetif

need_root() {
  if [ $UID != 0 ]; then
    echo "need to be root"
    exit 1
  fi
}

if [[ $1 == "" ]]; then
    echo "Usage : "
    echo "enable_nat [local_interface] [gateway_interface]"
    exit
fi

need_root

sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $1 -o $2 -j ACCEPT
