#!/bin/bash

echo "Monitoring : $1" 
inotifywait "$2" -m "$1" -e create -e moved_to -e modify |
    while read path action file; do
        echo "The file '$file' appeared in directory '$path' via '$action'"
    done
